package net.kismetwireless.android.smarterwifimanager.events;

/**
 * Created by dragorn on 12/14/14.
 */

/* Generated by:
    NETWORK_STATE_CHANGED_ACTION with no supplicant connection / valid network connection
 */
public class EventWifiDisconnected {
}
